### ISSUE TITLE
Status aller Datapoints

### ISSUE THREAD

**Issue by garosp** [hobbyquaker/RedMatic#105]
Hallo, habe eine Frage. 
Es geht mir darum den aktuellen Status aller Datapoints bei einem Start meiner Anwendung (läuft nicht auf der CCU) mittels mqtt zu erhalten. Bei einem Flow-Deploy oder Restart (auf der CCU) erhalte ich den Status aller Datapoints mittels mqtt-node übermittelt (alles gut). Kann ich dieses Verhalten ohne Flow-Restart von außen triggern oder gibt es einen RPC-Call der mir alle Werte liefert.

**Comment by hobbyquaker** [comment]
Du solltest eigentlich ohne weitere Maßnahmen schon alle Werte erhalten sobald Du ein MQTT Subscribe machst. Die Nachrichten werden (ausgenommen Tastendrücke) alle mit retain flag "gepublished", sollten also sofort nach einem subscribe in Deiner Anwendung eintrudeln.

**Comment by hobbyquaker** [comment]
Ergänzung: Damit das funktioniert muss allerdings sichergestellt sein dass in dem MQTT Output Node der letztlich den Publish macht bei "Retain" _nichts_ ausgewählt ist.
![image](https://user-images.githubusercontent.com/2503307/48804218-4eaeaf80-ed14-11e8-8302-982f51a059af.png)

**Comment by garosp** [comment]
Danke das wars
