### ISSUE TITLE
ping timeout HmIP-RF

### ISSUE THREAD

**Issue by Hypnos3** [hobbyquaker/RedMatic#11]
Hallo,

mich stören aktuell noch die "ping timeout HmIP-RF" Fehler:
```
May 27 12:08:33 homematic-ccu user.info node-red: [error] [ccu-connection:Homematic] ping timeout HmIP-RF 613
May 27 12:43:33 homematic-ccu user.info node-red: [error] [ccu-connection:Homematic] ping timeout HmIP-RF 706
May 27 12:56:03 homematic-ccu user.info node-red: [error] [ccu-connection:Homematic] ping timeout HmIP-RF 644
May 27 13:13:33 homematic-ccu user.info node-red: [error] [ccu-connection:Homematic] ping timeout HmIP-RF 669
```

Diese tauchen so auch als Debug-Meldungen auf.
Vielleicht kann man da noch was machen?

Danke & Gruß

**Comment by hobbyquaker** [comment]
Da muss eQ-3 wieder ran, sie hatten diesen Bug (das ping/pong nicht funktioniert) schon mal gefixed aber irgendwie kam er wieder ;-)
https://github.com/eq-3/occu/issues/79

**Comment by hobbyquaker** [comment]
hab es mal von "error" auf "warning" runtergestuft.

**Comment by Hypnos3** [comment]
Danke!
