### ISSUE TITLE
Link aus WebUI geht nicht

### ISSUE THREAD

**Issue by Hypnos3** [hobbyquaker/RedMatic#13]
Wenn ich den Button benutze:
![image](https://user-images.githubusercontent.com/12692680/40857607-e8bbbaca-65db-11e8-8fc2-0db891db4fe1.png)

leitet mich das zu "http://192.168.178.205/addons/red?sid=@3Eufzpuml3@"
das bringt folgende Seite:
![image](https://user-images.githubusercontent.com/12692680/40857644-034ac21e-65dc-11e8-9a72-c41d16d34033.png)

Wenn ich dann das "?sid=@3Eufzpuml3@" wegnehme, also nur "http://192.168.178.205/addons/red" aufrufe, geht es.

Meine Version ist aktuell: v1.0.0-beta.2+79

Ich bin mir ganz sicher bei welcher Version, aber das hat vor "kurzem" noch funktioniert.

Ich habe aber zwischenzeitlich auf eine neue SD Karte RaspberryMatic (Version 2.31.25.20180526) neu aufgespielt und NodeRed über die Backup Funktion wieder eingespielt, weil ich noch [andere](https://homematic-forum.de/forum/viewtopic.php?f=65&t=43359&start=20#p437308) Probleme habe.

**Comment by hobbyquaker** [comment]
Ist in v1.0.0-beta.4 behoben :-)

**Comment by Hypnos3** [comment]
Danke!!
Hab heute geupdatet --> get wieder.
