### ISSUE TITLE
issue: node update via "manage palette" not possible

### ISSUE THREAD

**Issue by holgerimbery** [hobbyquaker/RedMatic#14]
Hi Sebastian,
an update of a node via menu is not possible.
e.g. update of node "node-red-contrib-ccu" from 0.5.0 to 0.5.1 via menu will lead to an
error message: "failed to update:  module not locally installed"

Holger

**Comment by hobbyquaker** [comment]
Sollte jetzt funktionieren

**Comment by holgerimbery** [comment]
funktioniert- Danke!!
