### ISSUE TITLE
Programme werden nicht mehr ausgeführt

### ISSUE THREAD

**Issue by Hypnos3** [hobbyquaker/RedMatic#20]
Hallo,

ich hab mich lange nicht gemeldet, da ich aktuell RedMatic nicht mehr installiert habe.

Ich habe das Problem, das unter bestimmten Umständen die Programme under RaspberryMatic nicht mehr ausgeführt werden. ([Forum](https://homematic-forum.de/forum/viewtopic.php?f=65&t=43359))

Wenn das Problem auftritt, läuft die Rega für mich "normal". Die WebUI lässt sich aufrufen. Programme werden "scheinbar" normal getriggert und das Aktualisierungs-Datum wird geändert.
Auch manuell lassen sich Programme über die WebUI "starten" und das Aktualisierungsdatum wird angepasst.

Es werden aber keinerlei Aktionen getriggert. Das Betrifft auch Programme ohne Scripte. Also einfaches Schalten von Licht oder ähnliches geht nicht. Beim manuellen "starten" der Programme werden auch keine Aktionen des ersten Dann-Zweiges ausgeführt.

Im Log ist nichts auffälliges zu sehen, außer vielleicht das ScriptRuntimeError für Scripte auftreten, welche über POST direkt von einem Wemos auf der CCU ausgeführt werden.

Zum Testen hab ich mir ein einfaches Test-Programm erstellt:
![image](https://user-images.githubusercontent.com/12692680/41969198-efb9d50c-7a06-11e8-8a90-48b22e026a6e.png) (TEST-Arbeitszimmer  ist ein virtueller Kanal, K22_103_Licht Arbeitszimmer (40) ein wired Ausgang)
Wenn das Problem auftritt, geht mit dem Programm das Licht weder an noch aus. Die Kanäle lassen sich in dem Falle aber problemlos über die WebUI direkt schalten.

Das Problem tritt nach 1 bis 2 Tagen auf (meist innerhalb 24h).

Ein Neustart des Raspi über die WebUI löst das Problem. Alle Programme laufen danach wieder normal und auch keine ScriptRuntimeError.

Zuerst bin ich auf 2.31.25.20180225 (mit installiertem RedMatic ) zurück gegangen. Hier tritt das Problem nicht auf (aber da läuft RedMatic aber auch nicht richtig - siehe #1).

Dann bin ich auf 2.31.25.20180428 und hier lief RaspberryMatic ohne RedMatic stabil.
Mit RedMatic tauchten hier die Probleme das erste mal auf.
Jetzt bin ich auf 2.31.25.20180526 und auch hier gibt es keine Probleme ohne RedMatic.

Am Wochenende habe ich unter 2.31.25.20180526 RedMatic installiert (jungfreulich mit den Standard Flows - keine eigenen) und innerhalb von 6h hatte ich wieder das Problem. --> Gleich wieder das alte Backup zurückgespielt und keine Probleme mehr.

Ich habe RASPBERRY PI 2 MODEL B mit 183 Kanäle in 67 Geräten und 61 CUxD-Kanäle in 23 CUxD-Geräten

AddOns habe ich nur noch die folgenden installiert:
CUxD Daemon 2.0.0
HQ WebUI 2.5.4
HM-Tools 0.4.4
E-Mail 1.6.8
Programme Drucken 1.2a

Zusätzlich läuft noch IOBroker.

Ich denke zwar nicht, das RedMatic die Ursache des Problems ist, habe aber auch keine anderen Anhaltspunkte. Im Forum haben auch andere Nutzer das Problem ohne RedMatic.

Danke & Gruß

**Comment by hobbyquaker** [comment]
Um auszuschließen dass RedMatic diese Rega-Fehlfunktion verursacht würde ich empfehlen mal das Rega-Polling abzuschalten:

<img width="610" alt="rega" src="https://user-images.githubusercontent.com/2503307/41991888-4b85f506-7a47-11e8-89d8-94cd369e423d.png">

Außerdem würde ich dann auch dazu raten den ioBroker.hm-rega Adapter vorübergehend zu deaktivieren. Wenn das Problem dann nicht mehr auftritt bist mal einen Schritt weiter und kannst dann eins nach dem anderen wieder aktivieren und versuchen das zu reproduzieren.

**Comment by Hypnos3** [comment]
OK, Danke.
Habe RedMatic wieder installiert und das Rega polling abgeschaltet. Auch im IOBroker den Rege Adapter deaktiviert.
Mal abwarten.

**Comment by Hypnos3** [comment]
Das Problem ist gestern wieder aufgetreten. Jetzt scheint die CCU länger durchzuhalten, aber es tritt immer noch auf.
Ich beobachte noch weiter.

Ich befürchte ich komme nicht darum herum alles neu aufzusetzen. :(

**Comment by hobbyquaker** [comment]
Ich würde mal versuchen auf die "Standard" Rega umzuschalten, ich vermute Du nutzt die "Community" Version. Rein spekulativ: ich glaube Du läufst da in einen Rega Bug der nicht von externer Software verursacht wird - dessen Auftreten aber beschleunigt wird wenn Du externe Software auf die Rega zugreifen lässt. Auch wenn es wenig hilfreich ist für Dich komm ich nicht umhin es zu erwähnen: Ich habe meine Gründe warum ich seit 2014 die Rega überhaupt nicht mehr benutze, keine Variablen, keine Programme, keine Rega-Scripts ;-)

**Comment by Hypnos3** [comment]
Die Wahl der Logikschicht hat man bei RaspberryMatic nicht. Das gibt es nur bei der Standard CCU.

Durch die Probleme bin ich auch soweit, von der ReGa als Logikschicht wegzugehen. Hier bin ich aber noch nicht schlüssig was stattdessen nehmen soll. - Was nutzt du?

Für mich sollte es etwas sein, das auch auf dem selben Rechner (Raspi) läuft wie die CCU Software. - Wenn mal was nicht geht, potenzieren sich sonst die möglichen Fehlerquellen. Wenn man nur einen Raspi hat, kann im Problemfall auch mal jemand anderes das wieder zum laufen bekommen (Neustart/SD Karte tauschen - Backup SD Karte liegt direkt neben Raspi).

**Comment by hobbyquaker** [comment]
> Durch die Probleme bin ich auch soweit, von der ReGa als Logikschicht wegzugehen. Hier bin ich aber noch nicht schlüssig was stattdessen nehmen soll. - Was nutzt du?

Ich nutze https://github.com/hobbyquaker/mqtt-scripts auf einem x86 server, bei mir läuft alles über MQTT (Mosquitto als Broker). 

Wenn Du es auf der CCU bzw RaspberryMatic selbst laufen lassen willst - mit Node-RED sollte quasi auch alles möglich sein was mit der Rega Möglich ist. Manchmal ist etwas umdenken erforderlich -aufgrund des Nachrichtenfluß-Konzepts von Node-RED - aber wenn Du da vor Problemen stehst kannst gerne einfach hier nachfragen.
