### ISSUE TITLE
Harmony Hub steuern möglich?

### ISSUE THREAD

**Issue by TheRealTremes** [hobbyquaker/RedMatic#21]
Hallo, es ist zwar kein Fehler, aber ich wusste nicht wo ich meine Frage sonst stellen kann.

Kann man mit der RedMatic auch den Harmony Hub steuern um Aktionen starten zu können? Falls nein, ist das vorgesehen?

**Comment by hobbyquaker** [comment]
Sollte gehen, kann es aber mangels Harmony Hub selbst nicht testen.

Siehe: https://github.com/hobbyquaker/RedMatic/wiki/Erfolgreich-getestete-Nodes und https://github.com/hobbyquaker/RedMatic/wiki/Node-Installation
