### ISSUE TITLE
Paketinstallation über die Konsole geht nicht

### ISSUE THREAD

**Issue by Hypnos3** [hobbyquaker/RedMatic#22]
wenn ich versuche über die Kommandozeite ein Paket zu installieren:
`/usr/local/addons/redmatic/bin/npm install -g <paket-name>`

kommt:
`env: can't execute 'node': No such file or directory`

**Comment by hobbyquaker** [comment]
So, habe die Doku angepasst. Da ich die RedMatic executables nicht in den Pfad legen will (um nicht mit eventuellen anderen Node-basierten Addons zu kollidieren) ist es notwendig den redmatic bin path manuell hinzuzufügen:

```
export PATH=/usr/local/addons/redmatic/bin:$PATH
npm install -g <paket-name>
```

https://github.com/hobbyquaker/RedMatic/wiki/Node-Installation#Installation-via-Command-Line

**Comment by Hypnos3** [comment]
OK, Danke!
