### ISSUE TITLE
piVCCU + rmupdate

### ISSUE THREAD

**Issue by MathiasJZ** [hobbyquaker/RedMatic#23]
Ich habe gleich 2 Fragen:
Ist es möglich das Addon per rmupdate auf der Raspberrymatic zu installieren?
Da ein Bekannter seine Installation über piVCCU verwirklicht hat, auch auf dem Tinker board mit piVCCU? 
Ich weiß nicht, wo ich meine Fragen sonst stellen soll.
Gruß, Mathias

**Comment by hobbyquaker** [comment]
Install/Update/Uninstall via rmupdate sollte problemlos möglich sein.

Nutzung mit piVCCU ist denke ich auch möglich - aber aus meiner Sicht nicht wirklich Sinnvoll. Wenn man piVCCU nutzt kann man ja Node-RED auch einfach auf dem Wirts-System installieren oder einen weiteren Container dafür aufmachen.

**Comment by MathiasJZ** [comment]
Ok, danke!
Ich bin vorher lieber dann doch den herkömmlichen Weg gegangen, mit Neustart, weil ich nicht wußte, ob ein Neustart zwingend vorgeschrieben ist, dass Redmatic überhaupt läuft. Naja egal, es läuft jetzt. In Verbindung habe ich dann per rmupdate die Firmware aktuallisiert, was auch gut gelungen ist.
Für piVCCU muß ist erst mal gucken, ob der bekannte das überhaupt will.
danke jedenfalls für die ausführliche Antwort!
Gruß,
Mathias
