### ISSUE TITLE
Nach installation ping timeout Meldung im SysLog

### ISSUE THREAD

**Issue by libertyx82** [hobbyquaker/RedMatic#24]
Hallo,

nach der Installation habe ich im Syslog der CCU regelmäßig (ca alle 10-15 Minuten) folgende Meldung.

`homematic user.info node-red: [warn] [ccu-connection:localhost] ping timeout HmIP-RF 750`

Hm-IP Komponenten habe ich keine und ich habe auch an der standard Konfig nichts geändert.
Liegt das an einer Einstellung?

**Comment by hobbyquaker** [comment]
Wenn Du garkeine HmIP Komponenten nutzt kannst Du es im CCU Connection Node einfach deaktivieren, siehe https://github.com/hobbyquaker/RedMatic/wiki/CCU-Nodes#ccu-connection-node

**Comment by hobbyquaker** [comment]
#11
