### ISSUE TITLE
Xiaomi Smart home

### ISSUE THREAD

**Issue by MathiasJZ** [hobbyquaker/RedMatic#25]
Hallo Sebastian,
ich muß schon sagen, da hast Du wieder einmal großartige Arbeit abgeliefert!
Nun würde ich gerne wissen, ob es machbar ist, das Node für Xiaomi Smart Home zu installieren?
Davon habe ich schon einige am Arbeiten.
Derzeit gehe ich noch den Umweg über IObroker.
Gruß,
Mathias

**Comment by hobbyquaker** [comment]
Danke für das Lob :)

Bei Geräten die über das Gateway angebunden sind sollte das gehen, wenn Du direkt über Bluetooth mit den Geräten sprechen willst wird es (zumindest Stand heute) nicht gehen. 

Es gibt einige Nodes für Xiaomi, siehe https://flows.nodered.org/?term=xiaomi&type=node&num_pages=1
Über die Qualität dieser Nodes kann ich allerdings nichts sagen, das musst Du selbst herausfinden ;)

**Comment by MathiasJZ** [comment]
danke für die schnelle Antwort!
Das heißt, in meinem Fall muß es gehen :)
Dass es viele Xiaomi Nodes gibt, weiß ich. Nur welcher ist der richtige?
Ach ja, ich sah auch einen Vacuumcleaner-Node für Xiaomi, der geht doch auch, oder?
Gruß,
Mathias
