### ISSUE TITLE
Fehler "unknown interface BidCos-Wired"

### ISSUE THREAD

**Issue by Hypnos3** [hobbyquaker/RedMatic#26]
Bei jedem Deploy bekomme ich eine Reihe von Fehlermeldungen:
![image](https://user-images.githubusercontent.com/12692680/42539936-eeaebc18-849c-11e8-9e01-13766f08313f.png)

```

# cat /var/log/messages | grep red
Jul 11 00:02:19 homematic-ccu user.info node-red: [warn] Communication send error: Error: not opened
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] Stopping flows
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-sysvar:Anwesenheit] ccu-sysvar close
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-sysvar:Alarmzone 1] ccu-sysvar close
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-rpc-event:Wohnzimmer Temperatur] ccu-rpc-event close
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-rpc-event:UNREACH] ccu-rpc-event close
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-rpc-event:RPC event UNREACH] ccu-rpc-event close
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-sysvar:Anwesenheit] ccu-sysvar close
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-sysvar:Alarmzone 1] ccu-sysvar close
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-sysvar:Alarmzone 1_Text] ccu-sysvar close
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-sysvar:SV_SYS_TAGESZEIT_TYPE] ccu-sysvar close
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-sysvar:SV_SYS_TAGESZEIT] ccu-sysvar close
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-sysvar:SV_SYS_Firewall] ccu-sysvar close
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-sysvar:CCU_Reboot] ccu-sysvar close
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-rpc-event:ed72ca9a.15fe48] ccu-rpc-event close
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-rpc-event:3d3ff0e9.f63d6] ccu-rpc-event close
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-sysvar:SV_Say_Text] ccu-sysvar close
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-connection:Homematic] xmlrpc server closed
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [mqtt-broker:Mosquitto] Disconnected from broker: ccu@mqtt://localhost:1883
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-connection:Homematic] binrpc server closed
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] Stopped flows
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] Starting flows
Jul 11 00:09:16 homematic-ccu user.info node-red: [info] [ccu-connection:Homematic] paramsets loaded from /usr/local/addons/redmatic/var/ccu_paramsets.json
Jul 11 00:09:17 homematic-ccu user.info node-red: [info] [ccu-connection:Homematic] metadata loaded from /usr/local/addons/redmatic/var/ccu_localhost.json
Jul 11 00:09:17 homematic-ccu user.info node-red: [info] Started flows
Jul 11 00:09:18 homematic-ccu user.info node-red: [info] [mqtt-broker:Mosquitto] Connected to broker: ccu@mqtt://localhost:1883
Jul 11 00:09:22 homematic-ccu user.info node-red: [error] [ccu-connection:Homematic] rpc > BidCos-Wired setValue ["LEQ1286309:16","STATE",true] < Error: unknown interface BidCos-Wired
Jul 11 00:09:22 homematic-ccu user.info node-red: [error] [ccu-connection:Homematic] rpc > BidCos-Wired setValue ["LEQ1286365:15","STATE",true] < Error: unknown interface BidCos-Wired
Jul 11 00:09:22 homematic-ccu user.info node-red: [error] [ccu-connection:Homematic] rpc > BidCos-RF setValue ["LEQ0531665:1","STATE",false] < Error: unknown interface BidCos-RF
Jul 11 00:09:22 homematic-ccu user.info node-red: [error] [ccu-connection:Homematic] rpc > BidCos-Wired setValue ["LEQ1286309:13","STATE",false] < Error: unknown interface BidCos-Wired
Jul 11 00:09:22 homematic-ccu user.info node-red: [info] [ccu-connection:Homematic] rpc.createServer binrpc://127.0.0.1:2047
Jul 11 00:09:22 homematic-ccu user.info node-red: [info] [ccu-connection:Homematic] rpc.createServer http://127.0.0.1:2048
```

**Comment by hobbyquaker** [comment]
Hier versucht ein Value Node Werte zu setzen bevor die Verbindung zum Schnittstellenprozess aufgebaut ist. Gibt da verschiedene Workaround Ansätze das zu vermeiden. Wenn Du z.B. ein Inject Node nutzt mit "Inject once after Startup" kannst Du eine Verzögerung setzen, 2-3 sek sollten reichen. Man kann auch vermeiden dass bei jedem Deploy die Verbindungen getrennt und neu aufgebaut werden indem man nicht alles Deployed sondern nur geänderte Flows oder Nodes. 
<img width="306" alt="bildschirmfoto 2018-07-11 um 09 08 03" src="https://user-images.githubusercontent.com/2503307/42555915-2583579c-84ea-11e8-8cfa-7b1ec8e90e93.png">

Ich werde mir außerdem mal Gedanken machen wie ich bei setValue und RPC calls die direkt beim Start aufgerufen werden eine Queue einbauen kann die die Befehle dann erst abarbeitet wenn die Verbindung steht (https://github.com/hobbyquaker/node-red-contrib-ccu/issues/9) - das wäre dann eine saubere Läsung

**Comment by Hypnos3** [comment]
Wenn ich mir die "Geräte" mit dem Problem ansehe, haben diese gemeinsam, das diese von einem Ausgang einer anderen rpc node geschaltet wird, welche "Beim Start letzten bekannten Wert ausgeben" angehakt haben.

Leider finde ich kein schöneres Beispiel:
![image](https://user-images.githubusercontent.com/12692680/42558331-25d2cd0c-84f1-11e8-8657-0e2711deec1d.png)

Ich hab das jetzt für den "Startup" Fall verzögert und es kommt keine Meldung mehr:
![image](https://user-images.githubusercontent.com/12692680/42559757-5c213098-84f5-11e8-926c-97e6574f08af.png)

Zumindest kölnntest du es noch so gestalten, das die rpc-nodes bei "Beim Start letzten bekannten Wert ausgeben" ihren Wert erst dann aussenden, wenn alle anderen rpc nodes bereit sind.

**Comment by zetzi1** [comment]
Hi,
Ich habe ähnliches denke ich  dies bezieht sich allerdings auf eine ccu1 aber mit neustem xml.
Also es klappt schon mal im redmatic / nodered auf einem extra raspi  nur bekomme ich immer dies hier:


{ topic: "192.168.178.43/BidCos-Wired/Fr…", payload: true, ccu: "192.168.178.43", iface: "BidCos-Wired", device: "HEQ0024950" … }
9.12.2018, 15:27:39node: CCU1
msg : string[71]
" < BidCos-Wired ping Error: XML-RPC fault: ping: unknown method name"
9.12.2018, 15:27:54node: CCU1
msg : string[71]
" < BidCos-Wired ping Error: XML-RPC fault: ping: unknown method name"
9.12.2018, 15:28:09node: CCU1
msg : string[28]
"ping timeout BidCos-Wired 66"

was kann das sein ?  und zweite frage  kann mann die CCU1 gemeinsam in RedMatic einbinden ?

Gruß
Zetzi
