### ISSUE TITLE
rmupdate nicht möglich!

### ISSUE THREAD

**Issue by MathiasJZ** [hobbyquaker/RedMatic#28]
Wie ich schon vermutet habe:
Die Installation per rmupdate ist hier nicht möglich.
Da ich gedacht habe, an der Installation lief etwas schief, habe ich redmatic wieder deinstalliert, um es neu zu installieren.
Dieses mal habe ich es per rmupdate versucht.
Nach der Installation hatte ich gefühlte 1000 Meldungen.
Nach einer Installation auf dem "normalem" Weg hatte ich wieder vollen Zugriff auf Red node.
Gruß,
Mathias

**Comment by hobbyquaker** [comment]
Hmm. Hab grade ein bisschen mit rmupdate 1.12.4 getestet, Konnte Deinstallieren, Installieren und auch Updaten. Allerdings wird Node-RED nach Installation/Update nicht gestartet. Muss noch ein bisschen nachforschen und evtl Jan um Hilfe bitten. 
Falls Du es noch mal probierst wäre es hilfreich wenn Du eventuelle Fehlermeldungen hier postest.

**Comment by MathiasJZ** [comment]
Sebastian,
es sollte nur ein Test gewesen sein, nicht mehr
Da bei mir die SysVar nicht gingen,  habe ich erst an einen 
Installationsfehler geglaubt und auf "blöd" mal rmupdate versucht. Bei mir 
ist redmatic dann auch nicht mehr gelaufen.
Nach Installation redmatic 1.02 auf dem normalen Weg lief zwar redmatic 
wieder, aber die SysVar wollten immer noch nicht so recht.
Nachdem Du das Problem mit der Version 1.03 gefixt hast, ging es ja dann. 
Mit rmupdate habe ich es aber dann nicht mehr versucht.
Für mich ist das ja nicht unbedingt lebensnotwendig.
Gruß,
Mathias
