### ISSUE TITLE
Bearbeitung großer Flows langsam

### ISSUE THREAD

**Issue by Hypnos3** [hobbyquaker/RedMatic#32]
Zwischen Version v1.0.1 und v1.0.3 ist das Bearbeiten größerer Flows deutlich langsamer geworden.

Ich vermute, es liegt an der Anzeige des Verbindungsstatus.

**Comment by hobbyquaker** [comment]
Hoffe das mit node-red-contrib-ccu v1.1.2 bzw RedMatic v1.0.7 verbessert zu haben.

**Comment by Hypnos3** [comment]
Danke, hab es installiert und es wirkt zumindest wieder schneller.
