### ISSUE TITLE
rmupdate

### ISSUE THREAD

**Issue by MathiasJZ** [hobbyquaker/RedMatic#33]
Hi Sebastian, 
Die letzte Version von Redmatic ließ sich ohne weiteres per rmupdate aktualisieren. 
Die Version 1.0.6 nicht mehr.
Ich werde Updates nur noch im Zuge von Raspberrymatic FW-Updates anstoßen,  weil da dann sowieso ein Neustart ansteht.
Gruß, 
Mathias

**Comment by hobbyquaker** [comment]
Hmm... Bei meinen Tests hat es funktioniert. Irgendwelche Fehlermeldungen erschienen?

**Comment by hobbyquaker** [comment]
Eben noch mal getestet, mit rmupdate und einfach über Klick auf Aktualisieren update von 1.0.7 auf 1.0.8 gemacht, hat funktioniert.

**Comment by MathiasJZ** [comment]
Leider keine Fehlermeldung.
Es kann ja sein, dass es jetzt wieder geht. ich wollte die 1.0.6 installieren. Da ging es nicht.
Aber am 25.08. weiß ich mehr. da steht das nächste FW-Update an.
Gruß,
Mathias

**Comment by hobbyquaker** [comment]
Ich schließe das mal, alle meine Tests mit rmupdate waren bisher erfolgreich. Falls das Problem noch mal auftreten sollte bitte Bescheid geben
