### ISSUE TITLE
CUxD Kanäle

### ISSUE THREAD

**Issue by tafadafi** [hobbyquaker/RedMatic#37]
Hallo Sebastian,
vielleicht seh ich mal wieder den Wald vor lauter Bäumen nicht - aber ich finde meine
CUxD Devices nicht - dafür aber alle BidCos Geräte. Das Topic hatte Hypnos schon #5.

Hintergrund - möchte gerne Somfy Motoren mit Redmatic via Homematic steuern.

![20180726_161030](https://user-images.githubusercontent.com/24191662/43268086-fe3f5b38-90ef-11e8-9b15-4ccf66b500b4.jpg)

**Comment by hobbyquaker** [comment]
Sollte in v1.1.10 behoben sein.

**Comment by tafadafi** [comment]
Super ... funktioniert einwandfrei!
