### ISSUE TITLE
Fragen zu Dashboard, Einheit für Zahl anzeigen, Gauge, Dimmer ... 

### ISSUE THREAD

**Issue by juergen2908** [hobbyquaker/RedMatic#47]
Hallo,

bin im Bereich Node REd neu:

Habe mir das addon installiert. HM Licht Aktror im Dashboard einbinden habe geschafft, nur

jetzt hätte 2 Fragen:

ich schaffe es nicht meinen HM Dimmaktor einzubinden, bitte um eure hilfe:

habe es mal so versucht, da tut sich nichts:

```
[{"id":"dc579799.b6d8d8","type":"ccu-value","z":"cdb7abff.3cf718","name":"Licht Wohnzimmer","iface":"BidCos-RF","channel":"KEQxxxxx:1","datapoint":"LEVEL","mode":"","start":true,"change":true,"cache":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":470,"y":460,"wires":[[]]},{"id":"7ee16a2c.b14174","type":"function","z":"cdb7abff.3cf718","name":"Helligkeit","func":"var newMsg =  {\n        payload: {\"data\":{\"LEVEL\":msg.payload}}\n    };\nreturn newMsg;","outputs":1,"noerr":0,"x":250,"y":480,"wires":[["dc579799.b6d8d8"]]},{"id":"6493978c.4f9a38","type":"ui_slider","z":"cdb7abff.3cf718","name":"","label":"slider","group":"65a72644.483318","order":0,"width":0,"height":0,"passthru":true,"topic":"","min":0,"max":"100","step":1,"x":60,"y":480,"wires":[["7ee16a2c.b14174"]]},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048"},{"id":"65a72644.483318","type":"ui_group","z":"","name":"Geräte","tab":"fe205248.f04ed","disp":false,"width":"6","collapse":false},{"id":"fe205248.f04ed","type":"ui_tab","z":"","name":"Geräte","icon":"dashboard","order":1}]
```

Wie kann man homematic systemvariablen nur anzeigen lassen im Dashboard.

LG

Jürgen

**Comment by hobbyquaker** [comment]
Dimmer:
```
[{"id":"2ca831f3.26d90e","type":"ccu-value","z":"5c2958.3b4a96a8","name":"Licht Wohnzimmer","iface":"BidCos-RF","channel":"EEQ0012345:1","datapoint":"LEVEL","mode":"","start":true,"change":true,"cache":true,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":true,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":350,"y":160,"wires":[["6a84608.cb1d8a"]]},{"id":"6a84608.cb1d8a","type":"ui_slider","z":"5c2958.3b4a96a8","name":"","label":"slider","group":"f52ff66.52a6b08","order":0,"width":0,"height":0,"passthru":false,"topic":"","min":0,"max":"1","step":"0.01","x":330,"y":260,"wires":[["2ca831f3.26d90e"]]},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048"},{"id":"f52ff66.52a6b08","type":"ui_group","z":"","name":"Dimmer","tab":"fe205248.f04ed","disp":true,"width":"6","collapse":false},{"id":"fe205248.f04ed","type":"ui_tab","z":"","name":"Geräte","icon":"dashboard","order":1}]
```
Wichtig: Der Slider braucht den Wertebereich `0.00`-`1.00`, Step `0.01`. Die Checkbox ` If msg arrives on input, pass through to output` unbedingt deaktivieren, sonst hat man eine Endlosschleife gebaut. Den Kanal im Value Node musst Du natürlich noch anpassen.

Variable Anzeigen:
```
[{"id":"d1c9602e.0b9ab","type":"ccu-sysvar","z":"5c2958.3b4a96a8","name":"Anwesenheit","ccuConfig":"38263145.35ea0e","topic":"ReGaHSS/${Name}","x":240,"y":420,"wires":[["b8887291.ce654"]]},{"id":"b8887291.ce654","type":"ui_text","z":"5c2958.3b4a96a8","group":"46fbe67a.90cd18","order":0,"width":0,"height":0,"name":"","label":"Anwesenheit","format":"{{msg.payload}}","layout":"row-center","x":460,"y":420,"wires":[]},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048"},{"id":"46fbe67a.90cd18","type":"ui_group","z":"","name":"Variablen","tab":"36fb2145.947dee","disp":true,"width":"6","collapse":false},{"id":"36fb2145.947dee","type":"ui_tab","z":"","name":"Variablen","icon":"dashboard","order":2}]
```

**Comment by juergen2908** [comment]
Hallo,

danke für deine Anleitung.

Das mit den Dimmer funktioniert, besten Dank.

Nur die Systemvaribale wird nicht angezeigt, da der Wert eine Zahl ist, da wird text nicht gehen oder?

`
[{"id":"b75da79e.5c7048","type":"ui_text","z":"cdb7abff.3cf718","group":"65a72644.483318","order":0,"width":0,"height":0,"name":"Aussentemperatur","label":"°C","format":"{{msg.payload}}","layout":"row-center","x":590,"y":340,"wires":[]},{"id":"e532fb03.53afc8","type":"ccu-sysvar","z":"cdb7abff.3cf718","name":"Aussentemperatur","ccuConfig":"38263145.35ea0e","topic":"ReGaHSS/${Name}","x":370,"y":320,"wires":[["b75da79e.5c7048"]]},{"id":"65a72644.483318","type":"ui_group","z":"","name":"Geräte","tab":"fe205248.f04ed","disp":false,"width":"6","collapse":false},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048"},{"id":"fe205248.f04ed","type":"ui_tab","z":"","name":"Geräte","icon":"dashboard","order":1}]
`

**Comment by hobbyquaker** [comment]
Für das Beispiel mit der Anwesenheits-Variable kannst Du einen `change` Node nutzen um Text angezeigt zu bekommen (die Text-Darstellung steckt in der property `valueEnum`):

<img width="1048" alt="bildschirmfoto 2018-08-02 um 18 37 57" src="https://user-images.githubusercontent.com/2503307/43597718-37042a28-9683-11e8-96f4-a7ba67815982.png">

**Comment by juergen2908** [comment]
Hallo Hobbyquaker,
danke für deine Antwort.
Leider kommt da gar nichts wenn ich da so eingebe, also mit den set msg.payload :( ???
Macht das eh keinen Unterwschied, auch wenn es eine Zahl ist?
LG
Jürgen

**Comment by hobbyquaker** [comment]
Ah, da haben wir ein bisschen aneinander vorbeigeredet. Den Change-Node kannst Du weglassen - der ist so wie Du ihn jetzt benutzt wirkungslos, der wäre nur notwendig für so Variablen wie z.B. "Anwesenheit" die über eine Text-Darstellung ("Enum") verfügen. Um eine Zahl anzuzeigen reicht es direkt die Nachricht in den Dashboard-Text Node zu schicken:

<img width="341" alt="text" src="https://user-images.githubusercontent.com/2503307/43727616-ca84d05a-99a2-11e8-8763-173deea73d69.png">

Beispielflow:
```
[{"id":"287e02c6.b0c41e","type":"inject","z":"c4e07e8c.5bd93","name":"","topic":"","payload":"30.5","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":140,"wires":[["a51562a7.7801c"]]},{"id":"a51562a7.7801c","type":"ui_text","z":"c4e07e8c.5bd93","group":"46fbe67a.90cd18","order":0,"width":0,"height":0,"name":"","label":"Aussentemperatur:","format":"{{msg.payload}}°C","layout":"row-spread","x":360,"y":140,"wires":[]},{"id":"46fbe67a.90cd18","type":"ui_group","z":"","name":"Variablen","tab":"36fb2145.947dee","disp":true,"width":"6","collapse":false},{"id":"36fb2145.947dee","type":"ui_tab","z":"","name":"Variablen","icon":"dashboard","order":2}]
```

**Comment by hobbyquaker** [comment]
Ich glaube da ist ein Fehler in der Gauge-Config:
<img width="517" alt="bildschirmfoto 2018-08-06 um 18 40 22" src="https://user-images.githubusercontent.com/2503307/43729348-4e7a1474-99a8-11e8-820e-d19129b7d2c7.png">
Änder "Value Format" mal auf `{{msg.payload}}`

**Comment by juergen2908** [comment]
Hallo Hobbyquaker,

vielen Dank für deine Hilfe hat funktinoiert. Musste aber den Node-Red Dienst neu starten.

LG
Jürgen
