### ISSUE TITLE
Fehler unter RaspberryMatic

### ISSUE THREAD

**Issue by pzystorm** [hobbyquaker/RedMatic#48]
Ich habe RedMatic ganz frisch auf RaspberryMatic (2.35.16.20180715) installiert, bekomme nun jedoch komische Fehlermeldungen. Sorry, ich kann das gerade noch nicht präziser formulieren. Ich hoffe die Bilder sprechen mehr.

Hier habe ich versucht, einige Nodes zu disablen und wieder zu enablen:
![red1](https://user-images.githubusercontent.com/765650/43547823-b4a45130-95dc-11e8-9e61-b0bd62314b29.PNG)

'Unknown' ist sicherlich nicht normal, oder? Das sind keine von mir gebauten Skripts, sondern die Standard-Programme, die mit der Installation gekommen sind:
![red2](https://user-images.githubusercontent.com/765650/43547826-b67c9de6-95dc-11e8-8c63-3efac354b38e.PNG)

Hat jemand ne spontane Idee?

**Comment by hobbyquaker** [comment]
Was für ein Browser nutzt Du? Internet Explorer? :)

**Comment by pzystorm** [comment]
Aaaahrg... Bingo! :)
Das war mir nicht klar, dass der nicht geht.
Nutze nun Chrome und alles geht hervorragend.

**Comment by hobbyquaker** [comment]
Hab mal ein Hinweis in der Readme ergänzt :)
