### ISSUE TITLE
enhacement: sqlite / multi db node

### ISSUE THREAD

**Issue by schroejahr2** [hobbyquaker/RedMatic#51]
Hallo,
es wäre schön in zukunft die sqlite node zu integrieren, da das nachinstallieren nicht ohne weiteres funktioniert.

https://flows.nodered.org/node/node-red-node-sqlite

oder, direkt eine anbindung für MSSQL, MYSQL, SQLite, und PostgreSQL. : 

https://flows.nodered.org/node/node-red-contrib-sqldbs

das wäre super !

**Comment by hobbyquaker** [comment]
ich würd jetzt eher zu den node-red-node-* tendieren, das node-red-contrib-sqldbs scheint mir nicht maintained zu werden, 1 jahr kein commit und keine antworten auf issues...

**Comment by Sineos** [comment]
Wäre hier die Redis Einbindung nicht bevorzugt?

Als Storage backend hört sich das super an, gerade auf so Geräten wie dem RPi:
https://github.com/allenan/node-red-contrib-redis-storage 

Direkt von den NR Maintainern, aber leider nur out:
https://github.com/node-red/node-red-nodes/tree/master/storage/redis

Recht umfangreich aber wohl eher verlassen:
https://github.com/chameleonbr/node-red-contrib-redis

**Comment by hobbyquaker** [comment]
Redis geht quasi schon "out of the box", man kann node-red-node-redis über den Palette Manager nachinstallieren und ich hab auch schon ein Redis-Addon gebaut: https://github.com/hobbyquaker/ccu-addon-redis.
Bin aber auch grade dabei node-red-node-sqlite in RedMatic zu integrieren, will ich heute noch releasen. SQL hat ja auch was für sich, Jedem das Seine ;-)
btw - siehe auch https://github.com/hobbyquaker/RedMatic/issues/40 - Node-RED 0.19 wird persistente Context-Variablen einführen, wahlweise mit Dateisystem oder Redis als Storage Backend.

**Comment by hobbyquaker** [comment]
Grade mal probiert: `node-red-node-mysql` und `node-red-contrib-redis` ließen sich installieren.

**Comment by hobbyquaker** [comment]
So, v1.0.15 released, die beinhaltet nun node-red-node-sqlite.

**Comment by schroejahr2** [comment]
nur das backend fehlt dazu

**Comment by schroejahr2** [comment]
das vorherige kommentar war auf die node mysql bezogen. ich update mal !

**Comment by Sineos** [comment]
Vielen Dank für das Update

`Redis geht quasi schon "out of the box", man kann node-red-node-redis über den Palette Manager nachinstallieren`

Was ich bei node-red-node-redis nicht verstehe, ist dass diese nur ein `out` aber kein `in` hat. Ziemlich sinnfrei.

**Comment by hobbyquaker** [comment]
Jau, den `node-red-node-redis` versteh ich auch nicht - dafür ist `node-red-contrib-redis` um so mächtiger ;-)

> nur das backend fehlt dazu. bei sqlite ist es ja nur ne file.

Wenn Du es haben willst kann ich bei Gelegenheit auch mal ein ccu-addon-mysql bauen, sollte kein allzu großer act sein, auch wenn ich mir nicht ganz sicher bin ob es sinnvoll ist was das wenige RAM und den gemächlichen io einer SD-Karte angeht...

**Comment by schroejahr2** [comment]
genau das denke ich auch. sqlite ist sinnvoll mysql nicht.

Ich habe gerade schon meine flows auf die sqlite node migriert. funktioniert super, danke !

**Comment by schroejahr2** [comment]
hauptsächlich kam ich auf die sqlite idee, weil ich mit meinen bisjetzt begrenzten nodered kenntnissen ach einer möglichkeit gesucht habe einen durschnittsverbrauch von einem s0-bus stromzähler zu bauen (1000 impulse / kWh). 

Die einzige Lösung war mir sowas : 

timestamp = (new Date()).getTime();
    array = context.get('usage');
    if( array === undefined){
        array = [];
    }
    array.push(msg.timestamp);
 array = array.filter(t => t >= (timestamp - 60000));
context.set('usage',array);
    
    msg.payload = (array.length * 60 / 1000);
    return msg;


Aber nun logge ich alles inkl timestamp in die sqlite (neben anderen flows) und kann mir mit nem query alle möglichen arten an graphen ziehen. perfekt !

**Comment by Sineos** [comment]
Ich nehm für alle solche Themen: https://www.npmjs.com/package/node-red-contrib-aggregator
Super nützlich für IoT

**Comment by schroejahr2** [comment]
oh schönes teil danke für den hinweis.

sqlite ist in meinem fall perfekt da ich die daten gespeichert haben und beliebige graphen erstellen kann auch auf historische daten.

**Comment by hobbyquaker** [comment]
das "node-red-contrib-combine" dass ich mit redmatic mitliefer kann auch gleitende mittelwerte bilden (und einiges mehr) ;-)

**Comment by schroejahr2** [comment]
> das "node-red-contrib-combine" dass ich mit redmatic mitliefer kann auch gleitende mittelwerte bilden (und einiges mehr) ;-)

Das habe ich versucht aber ich bin vorerst gescheitert (wie gesagt node-red ist neu für mich).

Das Problem ist das ich halt unregelmässige messages mit ner 1 bekomme, und die anzahl davon über die letzten 60 sekunden haben will - aber bei jeder message aktualisiert - also auf den neuen zeitrahmen verschoben.

Vielleicht ist das möglich, mir zumindest war nicht direkt ersichtlich wie. dazu fehlt dann bei nodered die erfahrung.

**Comment by hobbyquaker** [comment]
Ja, ich muss mal an der Doku von den combine-Nodes arbeiten. Ich denke Dein Ziel müsstest Du erreichen mit dem combine - statistic Node, Timeout auf 60000 setzen, zum Zählen der Anzahl der Nachrichten stellst Payload auf "count". Distinction auf "_msg.id" setzen.
