### ISSUE TITLE
[Feature Request] DPInfo zu Systemvariablen ausgeben.

### ISSUE THREAD

**Issue by Hypnos3** [hobbyquaker/RedMatic#53]
Hallo,

wie kommt man in Redmatic an den Text eines ausgelösten Alarms.

Die Alarmvariable kann ich ja auslösen, aber der Text fehlt.
In HM Script komme ich über die DPInfo an diese Information: `dom.GetObject("Alarmzone 1").DPInfo();`

Mein Wunsch wäre bei Systemvariablen die DPInfo mit zu liefern. Wenn ich das richtig verstehe ist das bei anderen Variablen die Description.

Danke & Gruß
Robert

**Comment by hobbyquaker** [comment]
Hab es in node-red-contrib-ccu 1.1.19 implementiert, neuer RedMatic Build folgt die Tage, aber Du kannst auch jetzt schon node-red-contrib-ccu über den Palette Manager updaten. DPInfo steckt nun in der neuen Property `info`.

**Comment by hobbyquaker** [comment]
Ging doch schneller, steckt nun in RedMatic 1.1.0

**Comment by Hypnos3** [comment]
Vielen Dank!!
