### ISSUE TITLE
Probleme nach Installation neuer Nodes

### ISSUE THREAD

**Issue by Sineos** [hobbyquaker/RedMatic#56]
Beim mir kam es jetzt schon wiederholt zu seltsamen Effekten nach der Installation neuer Nodes über die Palette:

Fall 1:
```
getRegaPrograms Error: ENOENT: no such file or directory, open '/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/node_modules/homematic-rega/scripts/programs.rega'

getRegaPrograms Error: ENOENT: no such file or directory, open '/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/node_modules/homematic-rega/scripts/programs.rega'
```

Fall 2:
In diesem Fall waren schlicht alle CCU Node weg. Die Standard-Nodes und die zusätzlich installierten blieben erhalten.

In jedem Fall lies sich das einfach durch Neuinstallation von Redmatic beheben.

**Comment by Hypnos3** [comment]
Das kann ich bestätigen. Ist bei mir auch beim installieren und auch beim entfernen von Paketen aufgetreten.
Letztens erst beim entfernen des Context Browsers.

Tritt jedoch nicht jedes Mal auf.

**Comment by hobbyquaker** [comment]
in v1.1.1 mal ein erster versuch das zu fixen, allerdings bisschen blindflug, konnte das bei mir garnich reproduzieren. ich würde den issue mal offen lassen bis noch 2-3 redmatic releases erfolgt sind, gebt bitte bescheid falls es noch mal auftritt.

**Comment by Sineos** [comment]
Vielen Dank. Werde Rückmeldung geben.

**Comment by hobbyquaker** [comment]
@Sineos @Hypnos3 Kann ich diesen Issue schließen? Oder ist das Problem seit v1.1.1 noch mal aufgetreten?

**Comment by Sineos** [comment]
Ich hab nicht allzu viel installiert, aber bisher keine Probleme mehr gehabt 👍
