### ISSUE TITLE
WORKING datapoint, HmIP re-init on ping timeout fails

### ISSUE THREAD

**Issue by garosp** [hobbyquaker/RedMatic#59]
Hello Sebastian,
back again (roland). I hope this is the right, place, thx.
After installation of current redmatic and ccu it works so far. There is one question.  I define inject-nodes directly on ccu and remote node-environment. I can switch an old switch-actor and also a new one (HMIP). Works fine. The set true/false on the old one delivers two messages back (STATE and WORKING) the new one not. I don't understand the difference.
kind regards
roland

**Comment by hobbyquaker** [comment]
Ich vermute Dein HmIP Device hat einfach keinen Working Datenpunkt, deswegen bleibt er da aus. Die Dokumentation der Datenpunkte findest Du hier:
https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HM-Script_4-Datenpunkte.pdf
https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HmIP_Device_Documentation.pdf
Working gibt an ob ein Aktor im Moment dabei ist etwas zu tun, z.B. ob ein Rollladen Aktor den Rollladen gerade fahren lässt. Um Meldungen zu unterdrücken die während Working entstehen gibt es auch eine Checkbox in der `CCU Value` Node Konfiguration.

**Comment by garosp** [comment]
Ich habe auf der CCU-Seite nicht viel definiert anbei mein exportierter flow

[{"id":"8d47f7ab.d08888","type":"ccu-mqtt","z":"b7f590b6.cb4ea","name":"","ccuConfig":"be3abd26.0472b","cache":true,"topicOutputEvent":"raspmatic1/status/${channelName}/${datapoint}","topicInputSetValue":"raspmatic1/set/${channelNameOrAddress}/${datapoint}","topicOutputSysvar":"raspmatic1/status/${name}","topicInputSysvar":"raspmatic1/set/${name}","topicInputPutParam":"raspmatic1/paramset/${channelNameOrAddress}/${paramset}/${param}","topicInputPutParamset":"raspmatic1/paramset/${channelNameOrAddress}/${paramset}","topicInputRpc":"hm/rpc/${iface}/${method}/${command}/${callid}","topicOutputRpc":"hm/response/${callid}","payloadOutput":"mqsh-extended","x":330,"y":160,"wires":[["de350900.ff2d78","f0a9251a.a33948"]]},{"id":"de350900.ff2d78","type":"debug","z":"b7f590b6.cb4ea","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":510,"y":160,"wires":[]},{"id":"f239abbd.b74d38","type":"mqtt in","z":"b7f590b6.cb4ea","name":"","topic":"raspmatic1/#","qos":"2","broker":"101d00c9.d5b0df","x":130,"y":160,"wires":[["8d47f7ab.d08888"]]},{"id":"a2052bf5.8234a8","type":"inject","z":"b7f590b6.cb4ea","name":"","topic":"raspmatic1/set/JEQ0697296:1/STATE","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":260,"wires":[["8d47f7ab.d08888"]]},{"id":"7f0a4421.e00a3c","type":"inject","z":"b7f590b6.cb4ea","name":"","topic":"raspmatic1/set/JEQ0697296:1/STATE","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":320,"wires":[["8d47f7ab.d08888"]]},{"id":"f0a9251a.a33948","type":"mqtt out","z":"b7f590b6.cb4ea","name":"","topic":"","qos":"","retain":"","broker":"101d00c9.d5b0df","x":500,"y":220,"wires":[]},{"id":"27d9ff4f.d3bc6","type":"inject","z":"b7f590b6.cb4ea","name":"","topic":"raspmatic1/set/000218A98AD294:3/STATE","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":380,"wires":[["8d47f7ab.d08888"]]},{"id":"3777bbc6.de95b4","type":"inject","z":"b7f590b6.cb4ea","name":"","topic":"raspmatic1/set/000218A98AD294:3/STATE","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":440,"wires":[["8d47f7ab.d08888"]]},{"id":"be3abd26.0472b","type":"ccu-connection","z":"","name":"192.168.0.140","host":"192.168.0.140","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"192.168.0.140","rpcServerHost":"192.168.0.140","rpcBinPort":"2045","rpcXmlPort":"2046","contextStore":""},{"id":"101d00c9.d5b0df","type":"mqtt-broker","z":"","name":"Domotics","broker":"192.168.0.30","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""}]

![x](https://user-images.githubusercontent.com/25049526/44945220-7ca2e880-ade4-11e8-8fb8-27ded92db197.jpg)

ich war davon ausgegangen, dass ich nur den mqtt-Knoten brauche um die Kommkunikation von und zur CCU über mq zu gewährleisten. ich habe in der node-red instanz ausserhalb die gleichen inject-nodes und gehe über mq raus. wie gesagt schalten funktioniert aber die status-meldungen kommen nicht oder nur selten. ich dachte das der status aller komponenten über mq publish nach aussen geht. komisch war das es ohne änderungen gerade 2/3 schaltvorgänge ging, danach nicht mehr als ob die verbindung toggelt aus richtung ccu -> mqtt-node.

**Comment by hobbyquaker** [comment]
Oh, hatte Dich teilweise falsch verstanden. Kümmere mich asap darum.

**Comment by garosp** [comment]
Mit 1.4.5 steht die Verbindung länger aber nicht dauerhaft, nach restart mqtt-node läuft es wieder. Noch eine Info - der flow läuft auf der raspberrymatic mit localhost.

**Comment by hobbyquaker** [comment]
Kannst Du mal RedMatic auf Loglevel Debug stellen und ein Log-Auszug rund um den Zeitpunkt an dem die Verbindung verloren geht hier pasten?

**Comment by garosp** [comment]
hallo, 
anbei ein paar Auszüge. Sobald diese Meldung "ping timeout HmIP-RF 655" kommt erhalte ich keine Meldungen im Debug-Node mehr. der vollständigkeit halber - der homematic-schalter läuft in beiden richtungen weiter, hier steht die verbindung, bei dem ip-Schalter geht der rückweg nicht, schalten geht.

**in messages**

Sep 15 06:35:28 homematic-raspi daemon.info node-red[800]: [ccu-connection:192.168.0.140] HmIP-RF disconnected
Sep 15 06:35:28 homematic-raspi daemon.warn node-red[800]: [ccu-connection:192.168.0.140] ping timeout HmIP-RF 655
Sep 15 06:35:28 homematic-raspi daemon.info node-red[800]: [ccu-connection:192.168.0.140] HmIP-RF connected

**in Node-RED Debug erscheint** 

15.9.2018, 06:35:28node: 192.168.0.140
msg : string[24]
"ping timeout HmIP-RF 655"

**im hmserver.log**

Sep 15 06:35:28 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-2] (un)registerCallback on LegacyServiceHandler called from url: http://192.168.0.140:2046
Sep 15 06:35:28 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-2] init finished
Sep 15 06:35:28 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer INFO  [vert.x-worker-thread-1] Added InterfaceId: nr_HmIP-RF
Sep 15 06:39:04 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-6] SYSTEM: 0 Accesspoints in Queue
Sep 15 06:39:04 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-6] SYSTEM: Permanent-/Burstlistener Handler utilization: 0/50 used
Sep 15 06:39:04 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-6] SYSTEM: Eventlistener Handler utilization: 0/50 used

**Comment by garosp** [comment]
die timeout-meldungen kommen genau alle 10 minuten (10 * 60 * 1000), der reconnect scheint nicht immer zu funktionieren. jetzt um 06:51 nach einem weiteren connect läuft es wieder

Sep 15 06:45:28 homematic-raspi daemon.info node-red[800]: [ccu-connection:localhost] HmIP-RF disconnected
Sep 15 06:45:28 homematic-raspi daemon.warn node-red[800]: [ccu-connection:localhost] ping timeout HmIP-RF 615
Sep 15 06:45:28 homematic-raspi daemon.info node-red[800]: [ccu-connection:localhost] HmIP-RF connected

**Comment by garosp** [comment]
ich wage mal eine behauptung - kann es sein das du alle 10 minuten einen disconnect/connect machst - der disconnect noch nicht durch ist und deshalb der connect nicht funktioniert - beim nächsten mal nach 10 minuten ist der disconnect erledigt und der connect geht dann durch. das würde das bild 10 minuten geht es - dann wieder 10 minuten nicht - dann geht es wieder vielleicht erklären

**Comment by hobbyquaker** [comment]
Hab mal in node-red-contrib-ccu 1.6.3 versucht das zu beheben. Ist bisschen Blindflug, musst mal testen ob es damit funktioniert. Bis ich ein neues RedMatic release mach kannst Du auch schon vorab node-red-contrib-ccu in Node-RED über den Palette Manager updaten.

**Comment by hobbyquaker** [comment]
Mir ist eben noch was aufgefallen. In Deinen Logs taucht die IP Adresse `192.168.0.140` auf. Bei der Nutzung von RedMatic sollte das eigentlich nicht der Fall sein, das sollte alles über die Loopback Adresse `127.0.0.1` laufen. Kannst Du mir mal einen Screenshot der Konfiguration des "CCU Connection" Nodes zeigen (erreichbar über das Node-RED Menü -> Configuration Nodes)?

**Comment by garosp** [comment]
ich habe im mqtt-node die Einstellung auf localhost. Es gibt aber auch eine Config für 192.168.0.140, ich hatte da mal probiert. Habe die jetzt gelöscht. Im Moment läuft es schon seit 30 Minuten durch. Die 192.168.0.140 ist aber die ip der raspberrymatic. Bin immer noch auf node-red-contrib-ccu 1.4.5. Sorry wenn das die zweite config war, es wundert mich aber da sie nicht genutzt wurde.

![mqt](https://user-images.githubusercontent.com/25049526/45594892-aa6e5c80-b9a2-11e8-88f4-3f3bcd28d7b2.PNG)
![192-168-0-140](https://user-images.githubusercontent.com/25049526/45594894-b0643d80-b9a2-11e8-971f-f25ca2b6073a.PNG)
![localhost](https://user-images.githubusercontent.com/25049526/45594896-b6f2b500-b9a2-11e8-8c6f-a9271cf8891a.PNG)

**Comment by garosp** [comment]
Ja verstehe ich - gleicher init bei rpc-aufbau. Hatte schon gelöscht - es sieht so aus, dass es jetzt stabil läuft. Sorry das ich dir die arbeit gemacht habe.

**Comment by garosp** [comment]
verstehe aber nicht wieso er die anderen CCU-Definitionen, die ja im mqtt-node nicht angezogen werden nicht ignoriert. Kann man drauf reinfallen.

**Comment by hobbyquaker** [comment]
Die Connection Nodes bauen eine Verbindung zur CCU auf - egal ob sie in irgendeinem Node genutzt werden oder nicht. Werde mal drüber nachdenken ob ich das in Zukunft anders regeln kann. Dagegen spricht allerdings dass dann der erste Node den man einsetzt keine Autovervollständigung anbieten könnte da dann die Daten erst nach dem ersten Deploy zur Verfügung stehen würden, auch bisschen unschön.
Diesen Issue können wir dann erst mal schließen?
