### ISSUE TITLE
MQTT Node ChannelName

### ISSUE THREAD

**Issue by PSTobiasMueller** [hobbyquaker/RedMatic#60]
Hi,

ich probiere grade die neue MQTT Node aus. Ich hoffe damit demnächst dann meine Openhab Instanz ablösen zu können. Diese nutze ich im Moment noch als Übersetzer zwischen Node-Red und der CCU. Alles andere läuft eigentlich schon auf Node-Red.
Es scheint jedoch, das ein Topic mit Channel Name noch nicht so richtig angenommen wird von der MQTT Node.

Ich habe mal einen einfachen Flow gemacht in dem ich das Level eines Rolladens setzen will. In dem Fall: Rolladen_Spielzimmer_Shutter.
Schreibe ich als Topic: "hm/set/Rolladen_Spielzimmer_Shutter/LEVEL" bekomme ich die Fehlermeldung "no interface found for channel Rolladen_Spielzimmer_Shutter".
Nutze ich stattdessen den Channel hm/set/OEQ0892429:1/LEVEL funktioniert es.

Ist das noch ein Bug oder übersehe ich da einfach was?

Viele Grüße
Tobias

**Comment by hobbyquaker** [comment]
Sollte in node-red-contrib-ccu v1.4.5 gefixt sein. Bis es ein neues RedMatic Release gibt kannst Du das in Node-RED über den Palette Manager updaten, bitte gib Bescheid ob es dann wie erwartet funktioniert.

**Comment by PSTobiasMueller** [comment]
Perfekt. Danke!
Kleine Ursache, Große Wirkung.
