### ISSUE TITLE
reportValueUsage

### ISSUE THREAD

**Issue by Sineos** [hobbyquaker/RedMatic#61]
Referenz: https://github.com/jens-maus/RaspberryMatic/issues/399

Nachdem ich ein Dummy Programm eingesetzt habe, habe ich festgestellt, dass die Betätigung des `HM-PB-6-WM55` wieder mit der grünen LED bestätigt wird. Ich nehme an, das liegt an dem nun gesetzten `reportValueUsage`.
Dazu hätte ich nun ein paar Fragen an den Experten :-)

1. Macht es Sinn generell für die in RedMatic verwendeten Kanäle die RPC Methode `reportValueUsage` aufzurufen?
2. Wenn ja, alle Kanäle oder nur Sender wie z.B. der `HM-PB-6-WM55`
3. `reportValueUsage(String address, String value_id, Integer ref_counter)`
  - `address` ist klar
  - was ist `value_id`?
  - kann für `ref_counter` immer 1 gesetzt werden oder ist das abhängig von der Anzahl der Verwendungen?
4. Gibt es eine Art Rückkanal, sprich eine Bestätigung dass z.B. ein `PRESS_SHORT` verarbeitet wurde?

**Comment by Sineos** [comment]
Ich hab ein bisschen rumgespielt. Hier meine Beobachtungen:

**Dummy Rega Programm:**
- Setzt `reportValueUsage`
- Baut man ein Skript mit Fehlern als Dummy ein, wird trotzdem "grün" gesendet. Scheint also kein wirklich ausgewerteten Rückkanal zu geben
- Löscht man das Dummy Programm scheint `reportValueUsage` weiterhin gesetzt zu bleiben. Auch über einen Reboot hinweg


**reportValueUsage über RPC Node:**
- Verwendeter Parameter: `["OEQ0650679:4","PRESS_SHORT",1]`
- Bei der ersten Verwendung wird ein Fehler im Debug Fenster ausgegeben (Payload des return values ist `false`):
`rpc < binrpc method updateDevice not found: ["nr_BidCos-RF","OEQ0650679:4",1]`
- Funktioniert aber trotzdem und der Taster quittiert ab sofort mit grün
- `PRESS_SHORT` oder `PRESS_LONG` macht keinen Unterschied, scheint wirklich auf den Kanal zu gehen
- Es wird beim Taster ein `CONFIG_PENDING` Flag gesetzt
- Weitere Aufrufe der gleichen Methode werden ohne Fehler mit `payload = true` quittiert
- Mit `["OEQ0650679:4","PRESS_SHORT",0]` lässt sich das ganze löschen, d.h. kein grünes quittieren mehr
- Beim Löschen (0) tritt der Fehler nicht auf, es wird aber trotzdem als return `false` gesendet

Der Sinn von `reportValueUsage` entzieht sich mir noch etwas...

(was nichts dran ändert, dass mich der buggy `PRESS_LONG` nervt)

**Comment by hobbyquaker** [comment]
Der Fehler kommt daher dass der rfd mitteilt dass sich am Gerät was geändert hat (`updateDevice`), ich diese Methode aber bisher nicht implementiert hab. Habs mal auf die Todo genommen: https://github.com/hobbyquaker/node-red-contrib-ccu/issues/23
Noch eine Beobachtung die ich gemacht hab: manche Taster-Aktoren (ich glaube es waren Fernbedienungen, der 6-Fach Wandtaster und die Tasterschnittstelle) senden kein `PRESS_CONT` solange man kein `reportValueUsage` gesetzt hat, setzt man es kommt der Event.

**Comment by hobbyquaker** [comment]
Wichtiger Hinweis siehe https://github.com/jens-maus/RaspberryMatic/issues/399#issuecomment-421025442
