### ISSUE TITLE
Vorschlag fürs Wiki: Systeminformationen

### ISSUE THREAD

**Issue by Sineos** [hobbyquaker/RedMatic#62]
https://github.com/Sineos/redmatic-flow-sysinfo/blob/master/README_DE.md

Kommentare werden gerne genommen.

Einen Bug gibt es auch noch: Die farbliche Gestaltung der `Disk Free Tabelle` will nicht. Bei RSSI funktioniert es zumindest nachdem die erste Aktualisierung kam...manchmal hasse ich Computer (speziell html und Co) :-P

**Comment by hobbyquaker** [comment]
nice, klar verlink das! 👍

**Comment by Sineos** [comment]
erledigt
