### ISSUE TITLE
Device Namen auslesen

### ISSUE THREAD

**Issue by garosp** [hobbyquaker/RedMatic#68]
Hallo Stefan,
diesmal mit einer Frage. Ich würde gerne den Device Namen auslesen. Meine Suche im Netz und Versuche über unterschiedliche RPC-Requests waren bisher erfolglos.
VG Roland

**Comment by Hypnos3** [comment]
Die Namen von Geräten und Kanälen kommen soweit ich mal gelesen habe direkt von der RegaHss. Daher dürften diese über RPC nicht verfügbar sein.
Am Besten geht das Auslesen der Namen daher mit einem ReGa Script.

**Comment by garosp** [comment]
Danke für den Hinweis, hat mir weitergeholfen.
