### ISSUE TITLE
RedMatic 1.6.0 startet nicht auf RaspberryMatic

### ISSUE THREAD

**Issue by stan23** [hobbyquaker/RedMatic#69]
RedMatic 1.6.0 erstmals auf RaspberryMatic 3.37.8.20180929 installiert.

https://homematic-raspi.f17a/addons/redmatic/settings.cgi zeigt **stopped**.

Nach einem erzwungenen Reboot zeigt /var/log/messages bei jedem Versuch, RedMatic zu starten folgendes:

```
Oct  7 12:55:59 homematic-raspi user.info redmatic: RedMatic v1.6.0 (c) Sebastian Raff https://github.com/hobbyquaker/RedMatic
Oct  7 12:55:59 homematic-raspi user.info redmatic: Started Node-RED
Oct  7 12:56:01 homematic-raspi daemon.err node-red: module.js:550
Oct  7 12:56:01 homematic-raspi daemon.err node-red:     throw err;
Oct  7 12:56:01 homematic-raspi daemon.err node-red:     ^
Oct  7 12:56:01 homematic-raspi daemon.err node-red: Error: Cannot find module '/usr/local/addons/redmatic/lib/node_modules/node-red/red.js'
Oct  7 12:56:01 homematic-raspi daemon.err node-red:     at Function.Module._resolveFilename (module.js:548:15)
Oct  7 12:56:01 homematic-raspi daemon.err node-red:     at Function.Module._load (module.js:475:25)
Oct  7 12:56:01 homematic-raspi daemon.err node-red:     at Function.Module.runMain (module.js:694:10)
Oct  7 12:56:01 homematic-raspi daemon.err node-red:     at startup (bootstrap_node.js:204:16)
Oct  7 12:56:01 homematic-raspi daemon.err node-red:     at bootstrap_node.js:625:3
```

Die Datei existiert nicht:
> la /usr/local/addons/redmatic/lib/node_modules/node-red/
> LICENSE       node_modules

**Comment by hobbyquaker** [comment]
Hmm... Das ist seltsam, da scheinen bei der Installation einfach Dateien "verloren gegangen" zu sein, kann ich mir nicht erklären. Ich installiere grade mal RaspberryMatic und versuch das zu reproduzieren. Als Workaround könntest Du versuchen das addon .tar.gz auszupacken und händisch das redmatic Verzeichnis nach `/usr/local/addons` kopieren.

**Comment by stan23** [comment]
Das Leerzeichen kam von mir, ich habe mit der Zitierfunktion gekämpft. Ist oben korrigiert.

**Comment by hobbyquaker** [comment]
ah alles klar :) Ich würde empfehlen für Log Auszüge mit den ``` Tags zu arbeiten (müssen in einer eigenen Zeile stehen)

**Comment by stan23** [comment]
Ich habe die Installation offenbar vorzeitig abgebrochen, weil ich zu ungeduldig war :(
Hätte nicht gedacht dass der Raspi jemals so langsam sein könnte bei der Installation.

Nachdem ich das Addon drüberinstalliert habe, geht es.

Sorry für die Verwirrung°

**Comment by hobbyquaker** [comment]
Alles klar. Ja das kann sehr lange dauern, hab für Testzwecke hier ein uralten Raspberry Pi 1b, auf dem zieht sich das locker über ne viertel Stunde. Auf der CCU3 mit ihrem Pi 3b dauert es auch gefühlte 10 Minuten.
