### ISSUE TITLE
node-red-contrib-tahoma - keine Verbindung zu Somfy

### ISSUE THREAD

**Issue by taucher4000** [hobbyquaker/RedMatic#70]
Ich nutze seit kurzen die RedMatic Integration und möchte nun darüber auch meine mit Somfy gekoppelten Velux-Rolläden steuern. Dazu gibt das den Node https://github.com/nikkow/node-red-contrib-tahoma. Leider funktioniert dieser mit RedMatic nicht. Der Node bekommt nach der Eingabe des Benutzernamens/Passwords keine Verbindung. Nutze ich das gleiche außerhalb von RedMatic in einer nativen Red-Node instanz, so funktioniert der Node auf anhieb. Es scheint also ein Problem mit RedMatic zu sein. Die Log gibt leider auch mit dem Log-Level "Trace" nichts aus.

Hat jemand eine Idee?

https://github.com/nikkow/node-red-contrib-tahoma

**Comment by hobbyquaker** [comment]
Versuch mal in `/usr/local/addons/redmatic/var/node_modules/node-red-contrib-tahoma/tahoma.html` in Zeile 36 den führenden `/` aus der URL zu entfernen. Danach RedMatic neustarten und Weboberfläche neuladen. Wenn das funktioniert mach ich ein Pull Request beim node-red-contrib-tahoma Projekt auf, der führende Slash verhindert dass Node-RED auf einem anderen Pfad läuft (wie es bei RedMatic der Fall ist)

**Comment by taucher4000** [comment]
Hi Sebastian,

vielen Dank für die schnelle Antwort. Ich habe den / entfernt und schon funktioniert es. Ich würde mich über ein Pull freuen, damit es auch mit zukünftigen Versionen Kompatibel ist. 👍

**Comment by christianrit** [comment]
Hallo,
leider funktioniert die aktuelle node Version nicht auf Redmatic. 
Ich kann zwar die Verbindung zu somfy herstellen, aber ich sehe keine sites und keine Geräte.
den / zu entfernen habe ich versucht, jedoch steht dieser code jetzt in einer anderen Zeile.
beste Grüße und Danke im Voraus
