### ISSUE TITLE
Failed to update: Module not locally installed

### ISSUE THREAD

**Issue by Grewamor** [hobbyquaker/RedMatic#74]
Ich kann leider nicht "node-red-node-email" aktualisieren:

Fehler: 
![image](https://user-images.githubusercontent.com/18594343/47614395-a9e7dc00-da9f-11e8-9857-59fc1eaa4f15.png)

Ist da jemanden eine Lösung bekannt?

**Comment by hobbyquaker** [comment]
Die Nodes
* node-red-node-email
* node-red-node-feedparser
* node-red-node-rbe
* node-red-node-twitter
stecken im Lieferumfang von Node-RED mit drin und liegen daher nicht in dem Verzeichnis dass der Palette Manager bearbeiten kann. Warum das so angelegt ist versteh ich ehrlich gesagt auch nicht wirklich. 

Möglicher Workaround wäre es manuell zu löschen und danach wieder über den Palette Manager zu installieren:
```
export PATH=/usr/local/addons/redmatic/bin:$PATH
cd /usr/local/addons/redmatic/lib/node_modules/node-red
npm uninstall --unsafe-perm node-red-node-email
/etc/config/rc.d/redmatic restart
```
Siehe auch: https://groups.google.com/forum/#!topic/node-red/qqzx3qgBzBI

**Aber**: Das hat einen gravierenden Nachteil. Beim nächsten RedMatic Update würden es zwei mal rumliegen und ich weiss nicht welche Version Node-RED dann anziehen würde. Eine saubere Lösung muss so aussehen dass ich es schon im RedMatic-Installationspaket aus dem Node-RED Verzeichnis entferne und als zusaätzlichen Node mitliefer. Nehm ich auf die Todo.

**Comment by hobbyquaker** [comment]
Ab 1.7.13 sollte das Update der Node-RED standard Nodes über den Palette Manager funktionieren.
