### ISSUE TITLE
gerade oder ungerade Zahl Wochennummer

### ISSUE THREAD

**Issue by offbIRol** [hobbyquaker/RedMatic#75]
Hallo,
Wie kann man in Node-Red eine gerade oder ungerade Zahl auswerten?
In meinem Fall die Ausgabe der Wochennummer vom moment-Node als string.
Wie mach daraus ein true oder false?

**Comment by hobbyquaker** [comment]
In einem Function Node z.B. so:
```javascript
msg.payload = Boolean(msg.payload % 2);
return msg;
```
"x % 2" gibt Dir den Rest bei einer Ganzzahldivision. Ist dieser 0 - also x geradzahlig - konvertiert "Boolean()" das zu false, ist es ungerade zu true. Wenn Du es andersrum haben möchtest stell dem Boolean() ein Ausrufezeichen voran.

**Comment by offbIRol** [comment]
Vielen Dank für die schnelle Antwort!
Habs gleich ausprobiert, funktioniert wie gedacht.
Das erleichtert mir einiges. Cool.
