### ISSUE TITLE
node-red-contrib-xiaomi-miio funktioniert nicht

### ISSUE THREAD

**Issue by Christoph22** [hobbyquaker/RedMatic#76]
Würde gerne meinen Xiaomi Air Purifier einbinden.
Node node-red-contrib-xiaomi-miio wird ohne Fehler installiert, aber der Air Purifier wird nicht gefunden.

Die Node hat eine Abhängigkeit zu https://github.com/aholstenson/miio
ich denke es liegt daran

**Comment by hobbyquaker** [comment]
Führ mal auf Deiner CCU aus:
```
/usr/local/addons/redmatic/var/node_modules/node-red-contrib-xiaomi-miio/node_modules/.bin/miio discover
```

Kann ein bisschen dauern, aber dann sollte in der Ausgabe dieses Kommandos Dein Air Purifier erscheinen. Kann es leider selbst nicht verifizieren, hab nur ein Aqara Gateway, das findet er zumindest.

**Comment by hobbyquaker** [comment]
Ich würde vorschlagen mal hier die cacheTime wieder auf 1800 hochzusetzen:https://github.com/aformusatii/node-red-contrib-xiaomi-miio/blob/3d8619bb3921258a1c53603a9bdfeac19258d2b7/common/devices.js#L16 (`/usr/local/addons/redmatic/var/node_modules/node-red-contrib-xiaomi-miio/common/devices.js`), dann RedMatic neustarten, bisschen warten und nochma checken ob das Gerät dann gefunden wird. Falls das nicht klappt müsstest mal auf https://github.com/aformusatii/node-red-contrib-xiaomi-miio ein Issue aufmachen. Vermute dass das kein durch RedMatic verursachtes Problem ist, glaube eher n'Bug in dem node-red-contrib-xiaomi-miio. 
Vielleicht könnte aber auch https://github.com/Gromina/node-red-contrib-miio-wrapper eine Alternative sein, wobei node-red-contrib-xiaomi-miio schon ein besseren Eindruck macht.

**Comment by hobbyquaker** [comment]
Ich kenn diese miio lib nicht wirklich, aber vielleicht hilfts auch mal ein `/usr/local/addons/redmatic/var/node_modules/node-red-contrib-xiaomi-miio/node_modules/.bin/miio discover --sync` aufzurufen und dann RedMatic neuzustarten.

**Comment by Christoph22** [comment]
> Ich würde vorschlagen mal hier die cacheTime wieder auf 1800 hochzusetzen:https://github.com/aformusatii/node-red-contrib-xiaomi-miio/blob/3d8619bb3921258a1c53603a9bdfeac19258d2b7/common/devices.js#L16 (`/usr/local/addons/redmatic/var/node_modules/node-red-contrib-xiaomi-miio/common/devices.js`), dann RedMatic neustarten, bisschen warten und nochma checken ob das Gerät dann gefunden wird. Falls das nicht klappt müsstest mal auf https://github.com/aformusatii/node-red-contrib-xiaomi-miio ein Issue aufmachen. Vermute dass das kein durch RedMatic verursachtes Problem ist, glaube eher n'Bug in dem node-red-contrib-xiaomi-miio.
> Vielleicht könnte aber auch https://github.com/Gromina/node-red-contrib-miio-wrapper eine Alternative sein, wobei node-red-contrib-xiaomi-miio schon ein besseren Eindruck macht.

Dann funktioniert garnix mehr

![bildschirmfoto 2018-10-28 um 19 50 49](https://user-images.githubusercontent.com/44543595/47620502-fdcbe280-daea-11e8-8e75-86dccc61dd21.png)

**Comment by Christoph22** [comment]
> Ich kenn diese miio lib nicht wirklich, aber vielleicht hilfts auch mal ein `/usr/local/addons/redmatic/var/node_modules/node-red-contrib-xiaomi-miio/node_modules/.bin/miio discover --sync` aufzurufen und dann RedMatic neuzustarten.

![bildschirmfoto](https://user-images.githubusercontent.com/44543595/47620684-366cbb80-daed-11e8-9efe-76a919ba940b.jpg)

**Comment by hobbyquaker** [comment]
ah, ich glaub jetzt wird klar wo es hängt. Doch ein RedMatic Problem. miio versucht was im Homeverzeichnis zu persistieren, das geht auf einer CCU nicht. Ich überleg mal wie wir da ein Workaround bauen können, gib mir etwas Zeit.

**Comment by Christoph22** [comment]
Danke

**Comment by Christoph22** [comment]
Funktioniert 👍
