### ISSUE TITLE
Datenpunkt ist nicht bekannt

### ISSUE THREAD

**Issue by Hypnos3** [hobbyquaker/RedMatic#8]
Wahrscheinlich stelle ich mich hier wieder zu doof an.

Ich habe einen Datenpunkt (aus HQ WebUI):
![image](https://user-images.githubusercontent.com/12692680/40270279-3bda5e48-5b8a-11e8-954b-5117004b3f6f.png)

In Node-Red hab ich das folgendermaßen konfiguriert:
![image](https://user-images.githubusercontent.com/12692680/40270274-2202735c-5b8a-11e8-9d9f-736195580610.png)
Dabei gibt es aber nur STATE zur Auswahl:
![image](https://user-images.githubusercontent.com/12692680/40270292-842b9c48-5b8a-11e8-8a6a-845aa39a3bc9.png)

Will ich dem eine Frequenz zuweisen kommt auch ein Fehler:
![image](https://user-images.githubusercontent.com/12692680/40270289-6c8d101c-5b8a-11e8-8209-5c6b990765ba.png)

Der Fehler kommt auch, wenn ich den STATE Datenpunkt nehme.

**Comment by Hypnos3** [comment]
Das folgende Script funktioniert auch auf der CCU:
```
var fdp = (datapoints.Get("BidCos-Wired.NEQ0308096:13.FREQUENCY"));
fdp.State(1000);
```

**Comment by hobbyquaker** [comment]
Ich vermute dass da die ParamsetDescription für den 12/14 irgendwie unvollständig ist. Kannst Du mal im syslog schauen ob ccu-connection da eine "unknown paramsetDescription" Meldung o.ä erzeugt hat wenn Du versuchst auf FREQUENCY zu setzen?

**Comment by Hypnos3** [comment]
Also das ist ja was, 12500 als Number zu senden geht nicht, als String geht und als JSON `{"explicitDouble":12500}` geht auch.

**Comment by hobbyquaker** [comment]
Hab in v0.0.21 ein fallback auf String eingebaut falls eine Param-Beschreibung fehlt und man eine Number sendet.

**Comment by Hypnos3** [comment]
Danke! Super

**Comment by Hypnos3** [comment]
Es funktioniert mit der v0.0.22, nur kommt jetzt ein Fehler: "no description for [object Object] FREQUENCY"
Für mich ist das ok.

Dann die Frage: Issue offen lassen bis ParamsetDescriptions erzeugt werden oder schließen?

**Comment by hobbyquaker** [comment]
lass offen, dann gerät es nicht in vergessenheit. Die Fehlermeldung hielt ich für sinnvoll. So können wir mal sammeln bei welchen Geräten die ParamsetDescriptions fehlen. Allerdings sollte da nicht [object Object] sondern die Geräteadresse stehen  - "ein mal mit Profis..." ;-)

**Comment by hobbyquaker** [comment]
https://github.com/hobbyquaker/node-red-contrib-ccu/issues/5
