### ISSUE TITLE
[ccu-rpc:RPC listBidcosInterfaces] response timeout

### ISSUE THREAD

**Issue by taucher4000** [hobbyquaker/RedMatic#86]
Hi,

ich habe heute meine CCU3 auf  3.41.7 aktualisiert sowie RedMatic auf 1.7.16 . Nun habe ich das Problem, dass alle meine Homematic Komponenten ( BidCos-RF) auf disconnected stehen. nur die Homematic IP Komponenten sind online.

In der Debug-Console finde ich Meldungen wie:

Nov  3 22:21:17 ccu3 daemon.err node-red[841]: [ccu-connection:localhost]     < BidCos-RF listBidcosInterfaces Error: response timeout
Nov  3 22:21:17 ccu3 daemon.err node-red[841]: [ccu-rpc:RPC listBidcosInterfaces] response timeout

Irgend eine Idee, woran das liegen kann?

**Comment by hobbyquaker** [comment]
bin dran, mache Morgen ein neues Release mit den Anpassungen an die 3.41

**Comment by taucher4000** [comment]
also ein bekanntes Problem?

**Comment by hobbyquaker** [comment]
jup, siehe https://homematic-forum.de/forum/viewtopic.php?f=65&t=46478

**Comment by hobbyquaker** [comment]
related: #81

**Comment by taucher4000** [comment]
super, scheint alles wieder zu funktionieren. Vielen Dank!
