### ISSUE TITLE
Node for KNX

### ISSUE THREAD

**Issue by nanosonde** [hobbyquaker/RedMatic#92]
Hi!

Will this one work?
https://bitbucket.org/ekarak/node-red-contrib-knxjs

**Comment by hobbyquaker** [comment]
"sollte" gehen, soweit ich das überblicke ist das "pure" js, keine Binärmodule. Frage ist halt wie Du KNX anbindest, ob man EIBD oder Calimero auf der CCU zum laufen kriegt - keine Ahnung. Wenn Du ein KNX IP Router hast ists machbar vermute ich. Bin aber kein KNX Experte :) Im Zweifel: Probier es einfach aus

**Comment by nanosonde** [comment]
It works. ;)
It uses knxjs KNX stack which is written in pure Javascript(Node.js). 
Works with routing and tunneling mode. Mode is detected from the IP address that is used for connecting to the KNX gateway.
