### ISSUE TITLE
httpStatic

### ISSUE THREAD

**Issue by unixweb** [hobbyquaker/RedMatic#95]
Gibt es eine Möglichkeit die httpStatic in RedMatic einzubauen ?

Zum Beispiel unter : /usr/local/www

Standard ist bei Node-Red :
httpStatic: '/home/pi/node-red-static/',

Ich brauch es um Bilder in RedMatic einzubinden wie Webcams, Temperaturen , Fenster und Türen 

![bildschirmfoto 2018-11-13 um 16 56 47](https://user-images.githubusercontent.com/12023025/48425456-2dbeeb00-e765-11e8-9ace-3aaa504bb989.png)

![bildschirmfoto 2018-11-13 um 16 57 41](https://user-images.githubusercontent.com/12023025/48425528-4c24e680-e765-11e8-9ae3-51e21f54c0a0.png)

Danke und Grüße

**Comment by Sineos** [comment]
Eine Anleitung für httpStatic findest du hier:
https://github.com/Sineos/node-red-contrib-weatherman/blob/master/README_DE.md

**Comment by hobbyquaker** [comment]
siehe auch #50
