### ISSUE TITLE
missing datapoint for HM-WDS10-TH-O

### ISSUE THREAD

**Issue by drose28357** [hobbyquaker/RedMatic#99]
When reading a temperature and humidity sensor HM-WDS10-TH-O with a value node, you can not select humidity as an data point in the drop down list.

You can not enter "HUMIDITY" by keyboard. It will not be aceppted.. 

![red-node-missing-datapoint_humidity_in_hm-wds10-th-o](https://user-images.githubusercontent.com/11533286/48675321-ba97e900-eb57-11e8-8ff1-1ca5c13edb66.jpg)

**Comment by hobbyquaker** [comment]
Hmm... that's strange. Does the RPC Event Node offer the Humidity Datapoint?

**Comment by drose28357** [comment]
No. Thats the point. As you can see on the screenshot the drop down list only contains "TEMPERATURE"

**Comment by hobbyquaker** [comment]
did you try in the „rpc event“ node? screenshot show the „rpc value“ node.

**Comment by drose28357** [comment]
Yes, i just did it. I choose a room an the drop down list offers HUMIDITY.
That worked.

**Comment by drose28357** [comment]
Isn't there a node to read a value without event ? (well, i need a event to start readind annyway, i know)

**Comment by hobbyquaker** [comment]
hmm ok, it's only missing in the "rcp value" node and not in the "rpc event" node. That makes it even more difficult to find the cause of this error ;-) Will have to investigate. 
You said manually entering `HUMIDITY` is not accepted? How does that show up? You should be able to enter whatever you want (even invalid datapoints) in that input field, there should be no restriction.
To your question: not yet, it's doable through a workaround (saving values in the context and retrieving them with a change node again) but I'm working on a "get value" node to ease that usecase (#89)

**Comment by drose28357** [comment]
Manually entering ist possible, but when i click "Done" and reopen the node, datapoint is empty.
Even the deploay-button will not become red. => no change to the node

**Comment by drose28357** [comment]
Mist, habe das falsche Device erwischt. Habe einen Temperatursesor und einen Temperatur/Feutchte-Sensor dem Raum Garage zugeordnet und zuverlässig den flaschen erwischt. 

Bitte Issue schließen. 

Beim nächsten prüfe ich drei mal !!!! Versprochen.

**Comment by hobbyquaker** [comment]
hehe, kein ding, freut mich wenn die ursache gefunden wurde :)
